"""Uploaded files on a finite SD card.

Two live problems these tests lock down.

Deleting an account left every uploaded file behind. delete_account promises in
its own docstring to erase "the account and all associated data for good", but
removed only database rows — so every scan of a lab report, prescription photo
and picture of a rash stayed in uploads/ forever, with the row that identified
them gone. That is a privacy failure before it is a storage one.

Nothing noticed a filling disk. Arogo self-hosts on a Pi; when the card fills,
SQLite writes start failing, which in this app means a logged dose quietly not
saving.
"""
import os

import pytest

import auth as auth_module
from app import create_app
from db.core import init_db, user_context, execute, new_id, now_iso
from db import storage as st

PW = "stor-pw-12345"


@pytest.fixture(scope="module")
def app(tmp_path_factory):
    a = create_app()
    a.config["TESTING"] = True
    a.config["UPLOAD_FOLDER"] = str(tmp_path_factory.mktemp("uploads"))
    init_db()
    return a


@pytest.fixture(autouse=True)
def no_rate_limit():
    auth_module.reset_rate_limiter(); yield; auth_module.reset_rate_limiter()


@pytest.fixture(autouse=True)
def _app_ctx(app):
    """storage.upload_dir() reads current_app when there is one, so the tests
    exercise the same lookup the routes do."""
    with app.app_context():
        yield


def _uid(app, email):
    c = app.test_client()
    c.post("/auth/register", json={"email": email, "password": PW})
    return c, dict(execute("SELECT id FROM users WHERE email=?", (email,), fetchone=True))["id"]


def _write(app, name, content=b"x" * 100):
    path = os.path.join(app.config["UPLOAD_FOLDER"], name)
    with open(path, "wb") as fh:
        fh.write(content)
    return path


def _add_report(uid, filename):
    execute("""INSERT INTO reports (id, filename, original_name, patient_name,
                 report_type, report_date, upload_date, user_id)
               VALUES (?,?,?,?,?,?,?,?)""",
            (new_id(), filename, filename, "", "lab", "2026-08-01", now_iso(), uid),
            commit=True)


def _add_photo(uid, filename):
    execute("""INSERT INTO symptom_photos (id, label, filename, taken_date, created_at, user_id)
               VALUES (?,?,?,?,?,?)""",
            (new_id(), "Rash", filename, "2026-08-01", now_iso(), uid), commit=True)


# ── The registry must not drift ─────────────────────────────────────────────

def test_every_column_that_stores_a_filename_is_registered():
    """A new column holding a filename, left off FILE_COLUMNS, fails invisibly:
    files simply accumulate and nobody finds out until the card is full."""
    init_db()
    known = {(t, c) for t, c in st.FILE_COLUMNS}
    suspects = set()
    for table in ("reports", "symptom_photos", "medicines", "dependent_records",
                  "prescriptions", "vision_prescriptions"):
        try:
            cols = [r["name"] for r in execute(f"PRAGMA table_info({table})", fetchall=True)]
        except Exception:
            continue
        for col in cols:
            if col in ("filename", "photo_path", "file_path", "image_path"):
                suspects.add((table, col))
    missing = sorted(suspects - known)
    assert not missing, f"these store filenames but aren't in FILE_COLUMNS: {missing}"


def test_registered_columns_exist():
    init_db()
    for table, col in st.FILE_COLUMNS:
        cols = {r["name"] for r in execute(f"PRAGMA table_info({table})", fetchall=True)}
        assert col in cols, f"{table}.{col} is registered but doesn't exist"


# ── Ownership ───────────────────────────────────────────────────────────────

def test_files_owned_by_covers_every_registered_column(app):
    _, uid = _uid(app, "stor1@medeasy.test")
    _add_report(uid, "r1.pdf")
    _add_photo(uid, "p1.jpg")
    execute("""INSERT INTO medicines (id,name,frequency,times,active,created_at,user_id,photo_path)
               VALUES (?,?,?,?,?,?,?,?)""",
            (new_id(), "Metformin", "once_daily", '["09:00"]', 1, now_iso(), uid, "m1.jpg"),
            commit=True)
    assert st.files_owned_by(uid) == {"r1.pdf", "p1.jpg", "m1.jpg"}


def test_one_user_never_owns_anothers_files(app):
    _, a = _uid(app, "stor2a@medeasy.test")
    _, b = _uid(app, "stor2b@medeasy.test")
    _add_report(a, "mine.pdf")
    _add_report(b, "theirs.pdf")
    assert st.files_owned_by(a) == {"mine.pdf"}
    assert st.files_owned_by(b) == {"theirs.pdf"}


def test_a_traversal_in_a_stored_name_is_refused(app):
    """These values are fed to os.remove(). Everything here was generated by the
    app, but a row that somehow held "../../x" would make deletion catastrophic
    rather than merely wrong."""
    assert st._safe_name("../../etc/passwd") is None
    assert st._safe_name("sub/dir.pdf") is None
    assert st._safe_name("..") is None
    assert st._safe_name("") is None
    assert st._safe_name(None) is None
    assert st._safe_name("fine-name.pdf") == "fine-name.pdf"


def test_delete_files_ignores_an_unsafe_name(app, tmp_path):
    outside = tmp_path / "must-survive.txt"
    outside.write_text("important")
    st.delete_files(["../must-survive.txt", "../../must-survive.txt"])
    assert outside.exists(), "a traversal must never reach outside uploads/"


# ── The deletion right ──────────────────────────────────────────────────────

def test_deleting_an_account_removes_its_uploaded_files(app):
    """The headline bug: deleting an account erased the rows and left every
    medical document on disk."""
    from db.account import delete_account
    _, uid = _uid(app, "stor3@medeasy.test")
    _write(app, "scan-to-delete.pdf")
    _write(app, "rash-to-delete.jpg")
    _add_report(uid, "scan-to-delete.pdf")
    _add_photo(uid, "rash-to-delete.jpg")

    delete_account(uid)

    d = app.config["UPLOAD_FOLDER"]
    assert not os.path.exists(os.path.join(d, "scan-to-delete.pdf"))
    assert not os.path.exists(os.path.join(d, "rash-to-delete.jpg"))


def test_deleting_an_account_leaves_other_peoples_files_alone(app):
    from db.account import delete_account
    _, a = _uid(app, "stor4a@medeasy.test")
    _, b = _uid(app, "stor4b@medeasy.test")
    _write(app, "a-file.pdf"); _add_report(a, "a-file.pdf")
    _write(app, "b-file.pdf"); _add_report(b, "b-file.pdf")

    delete_account(a)

    d = app.config["UPLOAD_FOLDER"]
    assert not os.path.exists(os.path.join(d, "a-file.pdf"))
    assert os.path.exists(os.path.join(d, "b-file.pdf")), "erased a bystander's record"


# ── Restore ─────────────────────────────────────────────────────────────────

def test_a_restore_keeps_files_its_own_rows_still_reference(app):
    """A backup names the same files, so wiping them on restore would break
    every record it brings back."""
    from db.account import import_all_data
    _, uid = _uid(app, "stor5@medeasy.test")
    _write(app, "kept.pdf")
    _add_report(uid, "kept.pdf")
    backup = {"reports": [{"id": new_id(), "filename": "kept.pdf",
                           "original_name": "kept.pdf", "report_date": "2026-08-01",
                           "upload_date": now_iso()}]}
    import_all_data(uid, backup)
    assert os.path.exists(os.path.join(app.config["UPLOAD_FOLDER"], "kept.pdf"))
    assert st.files_owned_by(uid) == {"kept.pdf"}


def test_a_restore_removes_files_it_orphans(app):
    """A backup taken before a document was uploaded replaces the row that
    referenced it — leaving a file nothing can ever find again."""
    from db.account import import_all_data
    _, uid = _uid(app, "stor6@medeasy.test")
    _write(app, "orphaned-by-restore.pdf")
    _add_report(uid, "orphaned-by-restore.pdf")
    res = import_all_data(uid, {"reports": []})
    assert res["files_removed"] == 1
    assert not os.path.exists(
        os.path.join(app.config["UPLOAD_FOLDER"], "orphaned-by-restore.pdf"))


def test_a_failed_restore_does_not_delete_files(app, monkeypatch):
    """The rows survive a rollback, so their files must too."""
    from db.account import import_all_data
    import db.account as account
    _, uid = _uid(app, "stor7@medeasy.test")
    _write(app, "survives-failure.pdf")
    _add_report(uid, "survives-failure.pdf")

    monkeypatch.setattr(account, "_row_columns",
                        lambda row, cols: (_ for _ in ()).throw(RuntimeError("boom")))
    with pytest.raises(RuntimeError):
        import_all_data(uid, {"reports": [{"id": "x", "filename": "new.pdf"}]})
    monkeypatch.undo()

    assert os.path.exists(os.path.join(app.config["UPLOAD_FOLDER"], "survives-failure.pdf"))
    assert st.files_owned_by(uid) == {"survives-failure.pdf"}


# ── The report ──────────────────────────────────────────────────────────────

def test_orphans_are_found_but_not_removed_automatically(app):
    _, uid = _uid(app, "stor8@medeasy.test")
    _write(app, "referenced.pdf"); _add_report(uid, "referenced.pdf")
    _write(app, "nobody-owns-me.pdf", b"y" * 500)

    names = {o["name"] for o in st.find_orphans()}
    assert "nobody-owns-me.pdf" in names
    assert "referenced.pdf" not in names
    assert os.path.exists(os.path.join(app.config["UPLOAD_FOLDER"], "nobody-owns-me.pdf")), \
        "finding an orphan must not delete it — that decision is the owner's"


def test_a_referenced_but_missing_file_is_reported_as_missing_not_orphan(app):
    """A row promising a document that isn't there is a correctness problem —
    the page will offer a file that won't open — and it deserves its own name."""
    _, uid = _uid(app, "stor9@medeasy.test")
    _add_report(uid, "never-written.pdf")
    rep = st.storage_report(uid)
    assert any(m["name"] == "never-written.pdf" for m in rep["missing"])
    assert "never-written.pdf" not in {o["name"] for o in rep["orphans"]["files"]}


def test_report_measures_rather_than_estimates(app):
    _, uid = _uid(app, "stor10@medeasy.test")
    _write(app, "sized.pdf", b"z" * 4096)
    _add_report(uid, "sized.pdf")
    rep = st.storage_report(uid)
    assert rep["mine"]["bytes"] >= 4096
    assert rep["mine"]["files"] >= 1
    # Where a value can't be read it must be None, never a guessed number.
    assert rep["disk"]["free_bytes"] is None or rep["disk"]["free_bytes"] > 0


def test_low_space_is_a_measurement_not_a_mood(app):
    _, uid = _uid(app, "stor11@medeasy.test")
    rep = st.storage_report(uid)
    free = rep["disk"]["free_bytes"]
    if free is None:
        assert rep["low_space"] is False, "unknown free space is not a warning"
    else:
        assert rep["low_space"] == (free < rep["low_space_threshold_bytes"])


# ── Routes ──────────────────────────────────────────────────────────────────

def test_routes_require_auth(app):
    anon = app.test_client()
    assert anon.get("/api/storage").status_code == 401
    assert anon.delete("/api/storage/orphans").status_code == 401


def test_orphan_cleanup_removes_only_orphans(app):
    c, uid = _uid(app, "stor12@medeasy.test")
    _write(app, "keep-me.pdf"); _add_report(uid, "keep-me.pdf")
    _write(app, "drop-me.pdf")
    r = c.delete("/api/storage/orphans").get_json()
    assert r["success"] is True and r["removed"] >= 1
    d = app.config["UPLOAD_FOLDER"]
    assert os.path.exists(os.path.join(d, "keep-me.pdf"))
    assert not os.path.exists(os.path.join(d, "drop-me.pdf"))
