"""
db/action_plans.py — J3 emergency action plans. A plan is a titled, ordered list
of steps the user writes down from their own clinician: what to do in a specific
emergency (severe allergic reaction, asthma attack, low/high blood sugar…).

HONESTY: Arogo never supplies the medical steps. It offers blank title scaffolds
so a plan is easy to start, but every step is the user's own words (ideally
straight from their doctor). Nothing here is medical advice generated by the app.
"""
from .core import execute, current_user_id, new_id, now_iso, jdump, jload

# Title scaffolds only — NO pre-filled steps. Picking one starts an empty plan.
PLAN_SUGGESTIONS = (
    'Severe allergic reaction (anaphylaxis)',
    'Asthma attack',
    'Low blood sugar (hypoglycaemia)',
    'High blood sugar (hyperglycaemia)',
    'Seizure',
    'Chest pain',
)

_MAX_STEPS = 20


def _clean_steps(raw) -> list:
    if not isinstance(raw, list):
        return []
    out = []
    for s in raw[:_MAX_STEPS]:
        t = str(s or '').strip()
        if t:
            out.append(t[:300])
    return out


def list_action_plans() -> list:
    rows = execute("""SELECT * FROM action_plans WHERE user_id=?
                      ORDER BY sort_order, created_at""",
                   (current_user_id(),), fetchall=True) or []
    out = []
    for r in rows:
        d = dict(r)
        d['steps'] = jload(d.get('steps'), [])
        out.append(d)
    return out


def create_action_plan(data: dict) -> dict:
    title = str(data.get('title', '')).strip()
    if not title:
        raise ValueError('A plan title is required')
    pid = new_id()
    execute("""INSERT INTO action_plans (id, title, steps, sort_order, created_at, user_id)
               VALUES (?,?,?,?,?,?)""",
            (pid, title[:120], jdump(_clean_steps(data.get('steps', []))),
             0, now_iso(), current_user_id()), commit=True)
    row = dict(execute("SELECT * FROM action_plans WHERE id=?", (pid,), fetchone=True))
    row['steps'] = jload(row.get('steps'), [])
    return row


def update_action_plan(pid: str, data: dict) -> dict:
    uid = current_user_id()
    row = execute("SELECT * FROM action_plans WHERE id=? AND user_id=?", (pid, uid), fetchone=True)
    if not row:
        raise ValueError('Plan not found')
    cur = dict(row)
    title = str(data.get('title', cur['title'])).strip() or cur['title']
    steps = _clean_steps(data['steps']) if 'steps' in data else jload(cur.get('steps'), [])
    execute("UPDATE action_plans SET title=?, steps=? WHERE id=? AND user_id=?",
            (title[:120], jdump(steps), pid, uid), commit=True)
    out = dict(execute("SELECT * FROM action_plans WHERE id=?", (pid,), fetchone=True))
    out['steps'] = jload(out.get('steps'), [])
    return out


def delete_action_plan(pid: str) -> bool:
    execute("DELETE FROM action_plans WHERE id=? AND user_id=?",
            (pid, current_user_id()), commit=True)
    return True
