"""Uploaded files: who owns them, and what happens when nobody does.

Arogo self-hosts on a Raspberry Pi, so the uploads directory sits on an SD card
with a hard, fairly small limit and no ops team watching it. Two problems follow
from that, and both were live:

Deleting an account left every file behind. delete_account() promises, in its
own docstring, to erase "the account and all associated data for good" — but it
only ever removed database rows. Someone exercising their deletion right left
every scan of a lab report, every prescription photo and every picture of a rash
sitting in uploads/ indefinitely. That is a privacy failure first and a storage
leak second.

Nothing noticed a filling disk. When the card fills, SQLite writes start
failing — which in this app means a logged dose quietly not saving. The person
holding a pill in their hand has no way to know.

FILE_COLUMNS is the single source of truth for where a filename can live. A
conventions test fails the build when a new column stores one without being
listed here, because the failure mode of forgetting is invisible: files simply
accumulate, and nobody finds out until the card is full.
"""
import os

from .core import execute, current_user_id, DATA_TABLES

# (table, column) for every place a filename is stored. The column holds a bare
# name inside the uploads directory, never a path.
FILE_COLUMNS = [
    ('reports', 'filename'),            # uploaded medical records and scans
    ('symptom_photos', 'filename'),     # the photo journal
    ('medicines', 'photo_path'),        # a picture of the pill or its box
]


def upload_dir():
    """The uploads directory, resolved without needing a request context."""
    try:
        from flask import current_app
        return current_app.config['UPLOAD_FOLDER']
    except Exception:
        from config import Config
        return Config.UPLOAD_FOLDER


def _safe_name(name):
    """A stored filename must be a bare name inside uploads/.

    Everything here was generated by the app, so this should always hold — but
    these values are about to be fed to os.remove(), and a row that somehow
    contained "../../etc/something" would make deletion catastrophic rather than
    merely wrong. Cheap to check, and the one place it matters.
    """
    name = str(name or '').strip()
    if not name or name in ('.', '..'):
        return None
    if os.path.basename(name) != name:
        return None
    return name


def files_owned_by(uid) -> set:
    """Every filename this user's rows point at — including rows in their trash,
    which are still restorable and would be useless without their file."""
    owned = set()
    for table, col in FILE_COLUMNS:
        try:
            rows = execute(f"SELECT {col} AS f FROM {table} WHERE user_id=? AND {col} IS NOT NULL",
                           (uid,), fetchall=True) or []
        except Exception:
            continue                    # table not in this schema
        for r in rows:
            name = _safe_name(r.get('f'))
            if name:
                owned.add(name)
    try:
        from .trash import trashed_files
        owned |= trashed_files(uid)
    except Exception:
        pass
    return owned


def live_referenced_files() -> set:
    """Filenames pointed at by rows that are still in their own tables.

    Separate from all_referenced_files() because purging a trashed record needs
    to ask "is anything OTHER than the thing I'm deleting still using this file?"
    — and the trash can't be part of that answer, or an item could never release
    its own file.
    """
    referenced = set()
    for table, col in FILE_COLUMNS:
        try:
            rows = execute(f"SELECT {col} AS f FROM {table} WHERE {col} IS NOT NULL",
                           fetchall=True) or []
        except Exception:
            continue
        for r in rows:
            name = _safe_name(r.get('f'))
            if name:
                referenced.add(name)
    return referenced


def all_referenced_files() -> set:
    """Every filename ANY row points at, across all users, live or trashed. An
    orphan is a file on disk that appears in none of them.

    Deleted-but-restorable rows count. Without this the orphan sweep would erase
    the scan behind every record someone deleted this month, and a restore would
    hand them back an entry pointing at nothing.
    """
    referenced = live_referenced_files()
    try:
        from .trash import trashed_files
        referenced |= trashed_files()
    except Exception:
        pass
    return referenced


def delete_files(names) -> int:
    """Remove these files from the uploads directory. Returns how many went."""
    d = upload_dir()
    gone = 0
    for name in names:
        safe = _safe_name(name)
        if not safe:
            continue
        path = os.path.join(d, safe)
        try:
            if os.path.isfile(path):
                os.remove(path)
                gone += 1
        except OSError:
            pass                        # a locked or already-removed file is not fatal
    return gone


# Deliberately no delete_files_for_user(uid) convenience wrapper. Both callers
# must read the filenames BEFORE they delete the rows — the rows are the only
# record of which files are the user's — and delete them AFTER. A one-call
# helper invites exactly the wrong order, where it finds nothing and silently
# leaves every file behind, which is the bug this module exists to fix.


def _dir_size(path):
    total = count = 0
    try:
        with os.scandir(path) as it:
            for entry in it:
                try:
                    if entry.is_file():
                        total += entry.stat().st_size
                        count += 1
                except OSError:
                    pass
    except OSError:
        pass
    return total, count


# An upload is written to disk before its database row is committed, so for a
# moment a perfectly good file looks exactly like an orphan. Ignoring anything
# recent closes that window completely. Nothing needs cleaning up urgently — the
# files being hunted are months-old residue — so an hour costs nothing.
ORPHAN_GRACE_SECONDS = 3600


def find_orphans(min_age_seconds=ORPHAN_GRACE_SECONDS) -> list:
    """Files on disk that no row points at, with their size.

    These are the residue of account deletions and restores that happened before
    file cleanup existed. Listing them is deliberately separate from removing
    them: an orphan is, by definition, a file the app can no longer identify, so
    the decision to delete belongs to the person who owns the machine.

    Files younger than the grace period are never reported, because a file being
    uploaded right now is indistinguishable from an orphan — and this list is
    what a delete acts on, so a race here would destroy somebody's document
    seconds after they chose it.
    """
    import time
    d = upload_dir()
    referenced = all_referenced_files()
    cutoff = time.time() - max(0, min_age_seconds)
    out = []
    try:
        with os.scandir(d) as it:
            for entry in it:
                try:
                    if not entry.is_file() or entry.name in referenced:
                        continue
                    stat = entry.stat()
                    if stat.st_mtime > cutoff:
                        continue           # too new to be sure it's abandoned
                    out.append({'name': entry.name, 'bytes': stat.st_size})
                except OSError:
                    pass
    except OSError:
        return []
    return sorted(out, key=lambda e: -e['bytes'])


def _disk_free(path):
    try:
        import shutil
        u = shutil.disk_usage(path)
        return {'free_bytes': u.free, 'total_bytes': u.total}
    except Exception:
        return {'free_bytes': None, 'total_bytes': None}


# Below this much free space, a write can start failing — and a failing write in
# this app means a logged dose quietly not saving. Warn well before that.
LOW_SPACE_BYTES = 250 * 1024 * 1024


def storage_report(uid=None) -> dict:
    """What this install is using, and whether it is close to trouble.

    Every number here is measured, not estimated. Where something can't be read
    (a filesystem that won't report usage) the field is None rather than a guess.
    """
    uid = uid or current_user_id()
    d = upload_dir()
    total_bytes, total_files = _dir_size(d)

    mine = files_owned_by(uid)
    my_bytes = 0
    for name in mine:
        try:
            my_bytes += os.path.getsize(os.path.join(d, name))
        except OSError:
            pass                        # referenced but missing — counted below

    missing = [n for n in mine
               if not os.path.isfile(os.path.join(d, n))]
    orphans = find_orphans()

    db_bytes = None
    try:
        from .core import DB_PATH, IS_POSTGRES
        if not IS_POSTGRES and DB_PATH and DB_PATH != ':memory:':
            db_bytes = os.path.getsize(DB_PATH)
    except Exception:
        db_bytes = None

    disk = _disk_free(d)
    low = (disk['free_bytes'] is not None and disk['free_bytes'] < LOW_SPACE_BYTES)

    return {
        'uploads': {'bytes': total_bytes, 'files': total_files},
        'mine': {'bytes': my_bytes, 'files': len(mine)},
        # Referenced by a row but not on disk. Not a storage problem — a
        # correctness one: the record's page will offer a file that won't open.
        'missing': [{'name': n} for n in sorted(missing)],
        # Count and size only — never the names. An uploaded file is stored as
        # "<uuid>_<the name the user chose>", so listing orphans would hand one
        # user the original filenames of another's medical documents.
        'orphans': {'count': len(orphans), 'bytes': sum(o['bytes'] for o in orphans)},
        'database_bytes': db_bytes,
        'disk': disk,
        'low_space': low,
        'low_space_threshold_bytes': LOW_SPACE_BYTES,
    }
