"""
scripts/gen_api_docs.py — Regenerate docs/API.md from the live route map.

Run after adding/changing routes:  python scripts/gen_api_docs.py
"""
import os
import sys

os.environ.setdefault("MEDEASY_DB", ":memory:")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from app import create_app  # noqa: E402


def main():
    app = create_app()
    groups = {}
    for rule in app.url_map.iter_rules():
        if rule.endpoint.startswith('v1_') or rule.endpoint == 'static':
            continue
        if not rule.rule.startswith(('/api/', '/auth/')):
            continue
        blueprint = rule.endpoint.split('.')[0] if '.' in rule.endpoint else 'app'
        methods = sorted(rule.methods - {'HEAD', 'OPTIONS'})
        groups.setdefault(blueprint, []).append((rule.rule, methods))

    lines = [
        "# MedEasy API",
        "",
        "_Generated by `python scripts/gen_api_docs.py` — do not edit by hand._",
        "",
        "Every route below is also available under the versioned prefix",
        "`/api/v1` (e.g. `/api/medicines` → `/api/v1/medicines`,",
        "`/auth/token` → `/api/v1/auth/token`).",
        "",
        "## Authentication",
        "",
        "- **Web:** session cookie (`me_session`), set by `/auth/login`.",
        "- **Mobile / scripts:** `POST /auth/token` with `{email, password}`",
        "  returns `{token, token_type, expires_in}`; send it back as",
        "  `Authorization: Bearer <token>`. Tokens last 7 days and are all",
        "  revoked when the password changes.",
        "- Errors are JSON: `{\"error\": \"...\"}` with a matching status code.",
        "",
    ]
    for bp in sorted(groups):
        lines.append(f"## {bp}")
        lines.append("")
        lines.append("| Method | Path |")
        lines.append("|---|---|")
        for rule, methods in sorted(groups[bp]):
            lines.append(f"| {' '.join(methods)} | `{rule}` |")
        lines.append("")

    out = os.path.join(ROOT, "docs", "API.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    total = sum(len(v) for v in groups.values())
    print(f"docs/API.md written — {total} routes across {len(groups)} blueprints")


if __name__ == "__main__":
    main()
